
    "nl": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Bouwer', "shortDesc": 'Creëer en schaal softwareproducten die terugkerende inkomsten genereren.', "fullDesc": 'Software as a Service (SaaS) is de gouden standaard voor digitaal inkomen. Leer marktlacunes te identificeren, te bouwen met no-code of code tools, en een abonnementsbedrijf op te schalen.', "steps": [ { "title": 'Ideevorming', "desc": 'Vind winstgevende problemen om op te lossen.' }, { "title": 'MVP Bouw', "desc": 'Lanceer snel een werkend prototype.' }, { "title": 'Schalen', "desc": 'Verkrijg gebruikers en terugkerende inkomsten.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Beheers de kunst van overtuiging om alles met woorden te verkopen.', "fullDesc": 'Goede teksten maken miljoenen. Leer de psychologie achter overtuiging, hoe je landingspagina\'s, e-mails en advertenties schrijft die vreemden omzetten in klanten voor hoge tarieven.', "steps": [ { "title": 'Psychologie', "desc": 'Begrijp wat actie aandrijft.' }, { "title": 'Kaders', "desc": 'Beheers bewezen schrijfstructuren.' }, { "title": 'Klantenwerving', "desc": 'Haal goedbetaalde opdrachten binnen.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitale Marketing', "shortDesc": 'Draai winstgevende advertenties en beheer groei voor bedrijven.', "fullDesc": 'Elk bedrijf heeft meer klanten nodig. Start een bureau (SMMA) dat merken helpt groeien via Facebook Ads, TikTok Ads en Google Ads. Veel vraag, schaalbare service.', "steps": [ { "title": 'Advertentiestrategie', "desc": 'Leer winstgevende campagnes te draaien.' }, { "title": 'Dienstverlening', "desc": 'Genereer leads voor klanten.' }, { "title": 'Bureau Groei', "desc": 'Bouw een team voor vervullend werk.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Financiële Handel', "shortDesc": 'Analyseer markten en verhandel Crypto, Forex of Indexen.', "fullDesc": 'Beheers belangrijke technische analyseconcepten om financiële markten te navigeren. Leer risicobeheer, psychologie en strategieën om zelfstandig te profiteren van marktbewegingen.', "steps": [ { "title": 'Analyse', "desc": 'Lees grafieken en marktstructuur.' }, { "title": 'Risicobeheer', "desc": 'Bescherm eerst je kapitaal.' }, { "title": 'Uitvoering', "desc": 'Plaats transacties met hoge waarschijnlijkheid.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Content Creatie', "shortDesc": 'Bouw een persoonlijk merk en verdien aan je publiek.', "fullDesc": 'Aandacht is de nieuwe valuta. Leer hoe je virale short-form content maakt, een trouwe aanhang opbouwt en verdient via sponsoring, affiliates of je eigen producten.', "steps": [ { "title": 'Virale Scripts', "desc": 'Grijp kijkers direct.' }, { "title": 'Productie', "desc": 'Film en edit clips van hoge kwaliteit.' }, { "title": 'Monetarisatie', "desc": 'Zet views om in inkomen.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Verkoop fysieke producten wereldwijd zonder voorraad.', "fullDesc": 'Start een dropshipping of eigen merk webshop. Leer productonderzoek, leveranciersrelaties en hoe je een converterende winkel opbouwt op Shopify.', "steps": [ { "title": 'Product Jacht', "desc": 'Vind winnende producten.' }, { "title": 'Winkel Bouw', "desc": 'Ontwerp een site met hoge conversie.' }, { "title": 'Lancering', "desc": 'Drijf verkeer en vervul bestellingen.' } ] }
    ],
    "fr": [
        { "id": 'saas', "icon": '💻', "title": 'Créateur SaaS', "shortDesc": 'Créez et développez des logiciels générant des revenus récurrents.', "fullDesc": 'Le Software as a Service (SaaS) est la référence en matière de revenus numériques. Apprenez à identifier les besoins, à construire avec ou sans code, et à faire croître une activité par abonnement.', "steps": [ { "title": 'Idéation', "desc": 'Trouvez des problèmes rentables à résoudre.' }, { "title": 'Création MVP', "desc": 'Lancez rapidement un prototype fonctionnel.' }, { "title": 'Croissance', "desc": 'Acquérez des utilisateurs et des revenus récurrents.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Maîtrisez l\'art de la persuasion pour tout vendre avec des mots.', "fullDesc": 'Un bon texte rapporte des millions. Apprenez la psychologie de la persuasion, comment rédiger des pages de vente, des emails et des publicités qui convertissent les inconnus en clients.', "steps": [ { "title": 'Psychologie', "desc": 'Comprenez ce qui pousse à l\'action.' }, { "title": 'Structures', "desc": 'Maîtrisez les structures d\'écriture éprouvées.' }, { "title": 'Clients', "desc": 'Décrochez des contrats bien rémunérés.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Marketing Digital', "shortDesc": 'Gérez des publicités rentables et la croissance des entreprises.', "fullDesc": 'Toute entreprise a besoin de plus de clients. Lancez une agence (SMMA) aidant les marques à croître via Facebook Ads, TikTok Ads et Google Ads. Forte demande, service évolutif.', "steps": [ { "title": 'Stratégie', "desc": 'Apprenez à gérer des campagnes rentables.' }, { "title": 'Prestation', "desc": 'Générez des leads pour les clients.' }, { "title": 'Agence', "desc": 'Construisez une équipe pour le travail.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Trading Financier', "shortDesc": 'Analysez les marchés et tradez Crypto, Forex ou Indices.', "fullDesc": 'Maîtrisez l\'analyse technique pour naviguer sur les marchés financiers. Apprenez la gestion des risques, la psychologie et les stratégies pour profiter des mouvements du marché.', "steps": [ { "title": 'Analyse', "desc": 'Lisez les graphiques et la structure du marché.' }, { "title": 'Risque', "desc": 'Protégez d\'abord votre capital.' }, { "title": 'Exécution', "desc": 'Placez des trades à haute probabilité.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Création de Contenu', "shortDesc": 'Bâtissez une marque personnelle et monétisez votre audience.', "fullDesc": 'L\'attention est la nouvelle monnaie. Apprenez à créer du contenu viral court, à bâtir une audience fidèle et à gagner via le sponsoring, l\'affiliation ou vos propres produits.', "steps": [ { "title": 'Scripts Viraux', "desc": 'Accrochez les spectateurs instantanément.' }, { "title": 'Production', "desc": 'Filmez et montez des clips de qualité.' }, { "title": 'Monétisation', "desc": 'Transformez les vues en revenus.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Vendez des produits physiques mondialement sans stock.', "fullDesc": 'Lancez une boutique dropshipping ou une marque. Apprenez la recherche de produits, les relations fournisseurs et comment bâtir une boutique Shopify qui convertit.', "steps": [ { "title": 'Recherche', "desc": 'Trouvez des produits gagnants.' }, { "title": 'Boutique', "desc": 'Concevez un site à haute conversion.' }, { "title": 'Lancement', "desc": 'Attirez du trafic et expédiez les commandes.' } ] }
    ],
    "de": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Gründer', "shortDesc": 'Erstelle und skaliere Softwareprodukte mit wiederkehrenden Einnahmen.', "fullDesc": 'Software as a Service (SaaS) ist der Goldstandard für digitales Einkommen. Lerne Marktlücken zu finden, mit No-Code oder Code zu bauen und ein Abo-Geschäft zu skalieren.', "steps": [ { "title": 'Ideenfindung', "desc": 'Finde profitable Probleme.' }, { "title": 'MVP Bau', "desc": 'Starte schnell einen funktionierenden Prototyp.' }, { "title": 'Skalierung', "desc": 'Gewinne Nutzer und wiederkehrende Einnahmen.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Meistere die Kunst der Überzeugung, um alles mit Worten zu verkaufen.', "fullDesc": 'Gute Texte machen Millionen. Lerne die Psychologie der Überzeugung, wie man Landing Pages, E-Mails und Anzeigen schreibt, die Fremde in Kunden verwandeln.', "steps": [ { "title": 'Psychologie', "desc": 'Verstehe, was Handlungen auslöst.' }, { "title": 'Frameworks', "desc": 'Meistere bewährte Schreibstrukturen.' }, { "title": 'Kundengewinnung', "desc": 'Erhalte hochbezahlte Aufträge.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitales Marketing', "shortDesc": 'Schalte profitable Anzeigen und manage Wachstum für Firmen.', "fullDesc": 'Jedes Unternehmen braucht mehr Kunden. Starte eine Agentur (SMMA), die Marken hilft, durch Facebook Ads, TikTok Ads und Google Ads zu wachsen. Hohe Nachfrage, skalierbar.', "steps": [ { "title": 'Anzeigenstrategie', "desc": 'Lerne profitable Kampagnen zu schalten.' }, { "title": 'Dienstleistung', "desc": 'Generiere Leads für Kunden.' }, { "title": 'Agenturwachstum', "desc": 'Baue ein Team für die Arbeit auf.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Finanzhandel', "shortDesc": 'Analysiere Märkte und handle Krypto, Forex oder Indizes.', "fullDesc": 'Meistere technische Analyse, um Finanzmärkte zu navigieren. Lerne Risikomanagement, Psychologie und Strategien, um unabhängig von Marktbewegungen zu profitieren.', "steps": [ { "title": 'Analyse', "desc": 'Lese Charts und Marktstruktur.' }, { "title": 'Risikomanagement', "desc": 'Schütze zuerst dein Kapital.' }, { "title": 'Ausführung', "desc": 'Platziere Trades mit hoher Wahrscheinlichkeit.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Content Creation', "shortDesc": 'Baue eine Personal Brand und monetarisiere dein Publikum.', "fullDesc": 'Aufmerksamkeit ist die neue Währung. Lerne, virale Kurzvideos zu erstellen, eine treue Followerschaft aufzubauen und durch Sponsoring, Affiliates oder eigene Produkte zu verdienen.', "steps": [ { "title": 'Virale Skripte', "desc": 'Fessle Zuschauer sofort.' }, { "title": 'Produktion', "desc": 'Filme und schneide hochwertige Clips.' }, { "title": 'Monetarisierung', "desc": 'Verwandle Views in Einkommen.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-Commerce', "shortDesc": 'Verkaufe physische Produkte weltweit ohne Lagerbestand.', "fullDesc": 'Starte einen Dropshipping- oder Marken-Shop. Lerne Produktrecherche, Lieferantenbeziehungen und wie man einen konvertierenden Store auf Shopify baut.', "steps": [ { "title": 'Produktsuche', "desc": 'Finde Gewinnerprodukte.' }, { "title": 'Shop-Bau', "desc": 'Design eine High-Conversion-Seite.' }, { "title": 'Launch', "desc": 'Generiere Traffic und erfülle Bestellungen.' } ] }
    ],
    "mk": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Градител', "shortDesc": 'Креирајте и скалирајте софтверски производи со повторливи приходи.', "fullDesc": 'Софтверот како услуга (SaaS) е златниот стандард за дигитален приход. Научете како да идентификувате празнини на пазарот, да градите со no-code или код алатки и да скалирате бизнис со претплата.', "steps": [ { "title": 'Идеја', "desc": 'Најдете профитабилни проблеми за решавање.' }, { "title": 'MVP Изработка', "desc": 'Брзо лансирајте функционален прототип.' }, { "title": 'Скалирање', "desc": 'Стекнете корисници и повторливи приходи.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Совладајте ја уметноста на убедување за да продадете било што со зборови.', "fullDesc": 'Добар текст носи милиони. Научете ја психологијата зад убедувањето, како да пишувате целни страници, е-пошта и реклами кои ги претвораат странците во клиенти.', "steps": [ { "title": 'Психологија', "desc": 'Разберете што ја поттикнува акцијата.' }, { "title": 'Рамки', "desc": 'Совладајте докажани структури на пишување.' }, { "title": 'Клиенти', "desc": 'Обезбедете високо платени договори.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Дигитален Маркетинг', "shortDesc": 'Водете профитабилни реклами и управувајте со растот за бизниси.', "fullDesc": 'Секој бизнис има потреба од повеќе клиенти. Започнете агенција (SMMA) помагајќи им на брендовите да растат преку Facebook Ads, TikTok Ads и Google Ads. Голема побарувачка, скалабилна услуга.', "steps": [ { "title": 'Стратегија', "desc": 'Научете да водите профитабилни кампањи.' }, { "title": 'Испорака', "desc": 'Генерирајте потенцијални клиенти.' }, { "title": 'Раст на Агенција', "desc": 'Изградете тим за исполнителна работа.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Финансиско Тргување', "shortDesc": 'Анализирајте пазари и тргувајте Крипто, Форекс или Индекси.', "fullDesc": 'Совладајте ги клучните концепти на техничка анализа. Научете управување со ризик, психологија и стратегии за самостојно профитирање од пазарните движења.', "steps": [ { "title": 'Анализа', "desc": 'Читајте графикони и пазарна структура.' }, { "title": 'Ризик', "desc": 'Прво заштитете го својот капитал.' }, { "title": 'Извршување', "desc": 'Поставувајте трговии со висока веројатност.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Креирање Содржина', "shortDesc": 'Изградете личен бренд и монетизирајте ја својата публика.', "fullDesc": 'Вниманието е новата валута. Научете како да креирате вирална кратка содржина, да изградите лојални следбеници и да заработите преку спонзорства или сопствени производи.', "steps": [ { "title": 'Вирални Сценарија', "desc": 'Веднаш привлечете гледачи.' }, { "title": 'Продукција', "desc": 'Снимајте и монтирајте квалитетни клипови.' }, { "title": 'Монетизација', "desc": 'Претворете ги прегледите во приход.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Продавајте физички производи глобално без залиха.', "fullDesc": 'Започнете dropshipping или брендирана продавница. Научете истражување на производи и како да изградите продавница на Shopify што конвертира.', "steps": [ { "title": 'Потрага по Производи', "desc": 'Најдете победнички производи.' }, { "title": 'Изработка на Продавница', "desc": 'Дизајнирајте сајт со висока конверзија.' }, { "title": 'Лансирање', "desc": 'Донесете сообраќај и исполнете нарачки.' } ] }
    ],
    "mt": [
        { "id": 'saas', "icon": '💻', "title": 'Bennej SaaS', "shortDesc": 'Oħloq u skala prodotti tas-software li jiġġeneraw dħul rikorrenti.', "fullDesc": 'Software as a Service (SaaS) huwa l-istandard tad-deheb tad-dħul diġitali. Tgħallem kif tidentifika lakuni fis-suq, tibni bl-użu ta\' għodod no-code jew kodiċi, u tiskala negozju bbażat fuq abbonament.', "steps": [ { "title": 'Ideazzjoni', "desc": 'Sib problemi profittabbli biex issolvi.' }, { "title": 'Bini MVP', "desc": 'Niedi prototip li jaħdem malajr.' }, { "title": 'Skala', "desc": 'Akkwista utenti u dħul rikorrenti.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Ikkontrolla l-arti tal-persważjoni biex tbigħ xi ħaġa bil-kliem.', "fullDesc": 'Kopja tajba tagħmel miljuni. Tgħallem il-psikoloġija wara l-persważjoni, kif tikteb landing pages, emails, u reklami li jikkonvertu barranin fi klijenti għal tariffi għoljin.', "steps": [ { "title": 'Psikoloġija', "desc": 'Ifhem x\'imexxi l-azzjoni.' }, { "title": 'Oqfsa', "desc": 'Ikkontrolla strutturi ta\' kitba ppruvati.' }, { "title": 'Akkwist ta\' Klijenti', "desc": 'Assigura kuntratti bi ħlas għoli.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Marketing Diġitali', "shortDesc": 'Mexxi reklami profittabbli u mmaniġġja t-tkabbir għan-negozji.', "fullDesc": 'Kull negozju jeħtieġ aktar klijenti. Ibda aġenzija (SMMA) tgħin lill-marki jikbru permezz ta\' Facebook Ads, TikTok Ads u Google Ads. Domanda għolja, servizz skalabbli.', "steps": [ { "title": 'Strateġija tar-Reklami', "desc": 'Tgħallem tmexxi kampanji profittabbli.' }, { "title": 'Twassil tas-Servizz', "desc": 'Iġġenera leads għall-klijenti.' }, { "title": 'Tkabbir tal-Aġenzija', "desc": 'Ibni tim għal xogħol sodisfaċenti.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Kummerċ Finanzjarju', "shortDesc": 'Analizza s-swieq u nnegozja Kripto, Forex jew Indiċi.', "fullDesc": 'Ikkontrolla kunċetti ewlenin ta\' analiżi teknika biex tinnaviga fis-swieq finanzjarji. Tgħallem ġestjoni tar-riskju, psikoloġija u strateġiji biex tagħmel profitt mill-movimenti tas-suq b\'mod indipendenti.', "steps": [ { "title": 'Analiżi', "desc": 'Aqra charts u struttura tas-suq.' }, { "title": 'Ġestjoni tar-Riskju', "desc": 'Ipproteġi l-kapital tiegħek l-ewwel.' }, { "title": 'Eżekuzzjoni', "desc": 'Poġġi kummerċ bi probabbiltà għolja.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Ħolqien ta\' Kontenut', "shortDesc": 'Ibni marka personali u monetizza l-udjenza tiegħek.', "fullDesc": 'L-attenzjoni hija l-munita l-ġdida. Tgħallem kif toħloq kontenut virali f\'forma qasira, tibni segwaċi leali u taqla\' permezz ta\' sponsorships, affiljati jew prodotti tiegħek stess.', "steps": [ { "title": 'Skripts Virali', "desc": 'Iġbed lit-telespettaturi istantanjament.' }, { "title": 'Produzzjoni', "desc": 'Iffilmja u editja klipps ta\' kwalità għolja.' }, { "title": 'Monetizzazzjoni', "desc": 'Dawwar il-views fi dħul.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Biegħ prodotti fiżiċi globalment mingħajr ma żżomm inventarju.', "fullDesc": 'Ibda ħanut dropshipping jew tad-ditta. Tgħallem ir-riċerka tal-prodott, ir-relazzjonijiet mal-fornituri u kif tibni vetrina li tikkonverti fuq Shopify.', "steps": [ { "title": 'Kaċċa għall-Prodotti', "desc": 'Sib prodotti rebbieħa.' }, { "title": 'Bini tal-Ħanut', "desc": 'Iddisinja sit b\'konverżjoni għolja.' }, { "title": 'Tnedija', "desc": 'Mexxi traffiku u wettaq ordnijiet.' } ] }
    ],
    "me": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuće prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. Nauči kako prepoznati tržišne praznine, graditi koristeći no-code ili kod alate, i skalirati pretplatnički biznis.', "steps": [ { "title": 'Ideacija', "desc": 'Pronađi profitabilne probleme za rješavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuće prihode.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaš bilo šta riječima.', "fullDesc": 'Dobar tekst donosi milione. Nauči psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi šta pokreće akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaćene ugovore.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba više kupaca. Pokreni agenciju (SMMA) pomažući brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potražnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'Nauči voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'Generiši lidove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajući rad.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Finansijsko Trgovanje', "shortDesc": 'Analiziraj tržišta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj ključne koncepte tehničke analize za navigaciju finansijskim tržištima. Nauči upravljanje rizikom, psihologiju i strategije da profitiraš od tržišnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'Čitaj grafikone i strukturu tržišta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaštiti svoj kapital.' }, { "title": 'Izvršenje', "desc": 'Postavljaj trgovine visoke vjerovatnoće.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Kreiranje Sadržaja', "shortDesc": 'Izgradi lični brend i monetizuj svoju publiku.', "fullDesc": 'Pažnja je nova valuta. Nauči kako kreirati viralni kratki sadržaj, izgraditi lojalne pratioce i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledaoce.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visokog kvaliteta.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Prodaji fizičke proizvode globalno bez držanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. Nauči istraživanje proizvoda, odnose s dobavljačima i kako izgraditi konvertujuću trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'Pronađi pobjedničke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi saobraćaj i ispuni narudžbe.' } ] }
    ],
    "pt": [
        { "id": 'saas', "icon": '💻', "title": 'Criador SaaS', "shortDesc": 'Crie e escale produtos de software que geram receita recorrente.', "fullDesc": 'Software como Serviço (SaaS) é o padrão ouro da renda digital. Aprenda a identificar lacunas no mercado, construir usando ferramentas no-code ou código, e escalar um negócio baseado em assinatura.', "steps": [ { "title": 'Ideação', "desc": 'Encontre problemas lucrativos para resolver.' }, { "title": 'Construção MVP', "desc": 'Lance um protótipo funcional rápido.' }, { "title": 'Escala', "desc": 'Adquira usuários e receita recorrente.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Domine a arte da persuasão para vender qualquer coisa com palavras.', "fullDesc": 'Um bom texto faz milhões. Aprenda a psicologia por trás da persuasão, como escrever landing pages, e-mails e anúncios que convertem estranhos em clientes por altas taxas.', "steps": [ { "title": 'Psicologia', "desc": 'Entenda o que impulsiona a ação.' }, { "title": 'Estruturas', "desc": 'Domine estruturas de escrita comprovadas.' }, { "title": 'Aquisição de Clientes', "desc": 'Garanta contratos bem pagos.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Marketing Digital', "shortDesc": 'Rode anúncios lucrativos e gerencie o crescimento para empresas.', "fullDesc": 'Toda empresa precisa de mais clientes. Inicie uma agência (SMMA) ajudando marcas a crescer através de Facebook Ads, TikTok Ads e Google Ads. Alta demanda, serviço escalável.', "steps": [ { "title": 'Estratégia de Anúncios', "desc": 'Aprenda a rodar campanhas lucrativas.' }, { "title": 'Entrega de Serviço', "desc": 'Gere leads para clientes.' }, { "title": 'Crescimento da Agência', "desc": 'Construa uma equipe para trabalho gratificante.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Trading Financeiro', "shortDesc": 'Analise mercados e negocie Cripto, Forex ou Índices.', "fullDesc": 'Domine conceitos-chave de análise técnica para navegar nos mercados financeiros. Aprenda gestão de risco, psicologia e estratégias para lucrar com movimentos de mercado independentemente.', "steps": [ { "title": 'Análise', "desc": 'Leia gráficos e estrutura de mercado.' }, { "title": 'Gestão de Risco', "desc": 'Proteja seu capital primeiro.' }, { "title": 'Execução', "desc": 'Coloque ordens com alta probabilidade.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Criação de Conteúdo', "shortDesc": 'Construa uma marca pessoal e monetize sua audiência.', "fullDesc": 'Atenção é a nova moeda. Aprenda como criar conteúdo viral curto, construir seguidores leais e ganhar através de patrocínios, afiliados ou seus próprios produtos.', "steps": [ { "title": 'Roteiros Virais', "desc": 'Prenda os espectadores instantaneamente.' }, { "title": 'Produção', "desc": 'Filme e edite clipes de alta qualidade.' }, { "title": 'Monetização', "desc": 'Transforme visualizações em renda.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Venda produtos físicos globalmente sem manter estoque.', "fullDesc": 'Comece uma loja de dropshipping ou marca própria. Aprenda pesquisa de produtos, relações com fornecedores e como construir uma vitrine que converte na Shopify.', "steps": [ { "title": 'Caça de Produtos', "desc": 'Encontre produtos vencedores.' }, { "title": 'Construção da Loja', "desc": 'Desenhe um site de alta conversão.' }, { "title": 'Lançamento', "desc": 'Direcione tráfego e cumpra pedidos.' } ] }
    ],
