
import json
import re

path = r"c:\Users\amadej\Desktop\moja-spletna-stran\flowstackai.github.io\dashboard.html"

# Correct Content Data with proper emojis and characters
content_data = {
    "en": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Builder', "shortDesc": 'Create and scale software products that generate recurring revenue.', "fullDesc": 'Software as a Service (SaaS) is the gold standard of digital income. Learn how to identify market gaps, build using no-code or code tools, and scale a subscription-based business.', "steps": [ { "title": 'Ideation', "desc": 'Find profitable problems to solve.' }, { "title": 'MVP Build', "desc": 'Launch a working prototype fast.' }, { "title": 'Scale', "desc": 'Acquire users and recurring revenue.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Master the art of persuasion to sell anything with words.', "fullDesc": 'Good copy makes millions. Learn the psychology behind persuasion, how to write landing pages, emails, and ads that convert strangers into customers for high fees.', "steps": [ { "title": 'Psychology', "desc": 'Understand what drives action.' }, { "title": 'Frameworks', "desc": 'Master proven writing structures.' }, { "title": 'Client Acquisition', "desc": 'Land high-paying retainers.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digital Marketing', "shortDesc": 'Run profitable ads and manage growth for businesses.', "fullDesc": 'Every business needs more customers. Start an agency (SMMA) helping brands grow through Facebook Ads, TikTok Ads, and Google Ads. High demand, scalable service.', "steps": [ { "title": 'Ad Strategy', "desc": 'Learn to run profitable campaigns.' }, { "title": 'Service Delivery', "desc": 'Generate leads for clients.' }, { "title": 'Agency Growth', "desc": 'Build a team to fulfilling work.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Financial Trading', "shortDesc": 'Analyze markets and trade Crypto, Forex, or Indices.', "fullDesc": 'Master key technical analysis concepts to navigate financial markets. Learn risk management, psychology, and strategies to profit from market movements independently.', "steps": [ { "title": 'Analysis', "desc": 'Read charts and market structure.' }, { "title": 'Risk Mgmt', "desc": 'Protect your capital first.' }, { "title": 'Execution', "desc": 'Place high-probability trades.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Content Creation', "shortDesc": 'Build a personal brand and monetize your audience.', "fullDesc": 'Attention is the new currency. Learn how to create viral short-form content, build a loyal following, and monetize through sponsorships, affiliates, or your own products.', "steps": [ { "title": 'Viral Scripts', "desc": 'Hook viewers instantly.' }, { "title": 'Production', "desc": 'Film and edit high-quality clips.' }, { "title": 'Monetization', "desc": 'Turn views into income.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Sell physical products globally without holding inventory.', "fullDesc": 'Start a dropshipping or BRANDED e-commerce store. Learn product research, supplier relations, and how to build a converting storefront on Shopify.', "steps": [ { "title": 'Product Hunt', "desc": 'Find winning products.' }, { "title": 'Store Build', "desc": 'Design a high-converting site.' }, { "title": 'Launch', "desc": 'Drive traffic and fulfill orders.' } ] }
    ],
    "sl": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Razvijalec', "shortDesc": ' ustvari in prodajaj programsko opremo z mesečno naročnino.', "fullDesc": 'Software as a Service (SaaS) je zlati standard digitalnega zaslužka. Nauči se prepoznati tržne priložnosti, zgraditi rešitev (no-code ali koda) in skalirati posel.', "steps": [ { "title": 'Ideja', "desc": 'Najdi dobičkonosne probleme.' }, { "title": 'MVP Izdelava', "desc": 'Hitro lansiraj delujoč prototip.' }, { "title": 'Rast', "desc": 'Pridobi uporabnike in redne prihodke.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Obvladaj umetnost prepričevanja in prodajaj z besedami.', "fullDesc": 'Dobra besedila prinašajo milijone. Spoznaj psihologijo prodaje, kako pisati pristajalne strani, emaile in oglase, ki obiskovalce spremenijo v kupce.', "steps": [ { "title": 'Psihologija', "desc": 'Razumej, kaj sproži akcijo.' }, { "title": 'Formule', "desc": 'Uporabi preverjene strukture pisanja.' }, { "title": 'Pridobivanje strank', "desc": 'Dobi visoko plačane projekte.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitalni Marketing', "shortDesc": 'Upravljaj dobičkonosne oglase za podjetja (SMMA).', "fullDesc": 'Vsako podjetje potrebuje več strank. Odpri agencijo in pomagaj znamkam rasti s Facebook, TikTok in Google oglasi. Visoko povpraševanje, skalabilno.', "steps": [ { "title": 'Strategija', "desc": 'Nauči se voditi profitabilne kampanje.' }, { "title": 'Rezultati', "desc": 'Generiraj leade za stranke.' }, { "title": 'Rast Agencije', "desc": 'Zgradi ekipo in delegiraj delo.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Trading', "shortDesc": 'Analiziraj trge in trguj s Kripto, Forex ali Indeksi.', "fullDesc": 'Obvladaj tehnično analizo in finančne trge. Nauči se obvladovanja tveganja, psihologije in strategij za samostojno profitabilno trgovanje.', "steps": [ { "title": 'Analiza', "desc": 'Branje grafov in tržne strukture.' }, { "title": 'Tveganje', "desc": 'Najprej zaščiti svoj kapital.' }, { "title": 'Izvedba', "desc": 'Izvajaj posle z visoko verjetnostjo.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Ustvarjanje Vsebin', "shortDesc": 'Zgradi osebno znamko in monetiziraj občinstvo.', "fullDesc": 'Pozornost je nova valuta. Nauči se ustvarjati viralne kratke videe, zgraditi zvesto skupnost in služiti s sponzorstvi ali lastnimi produkti.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Takoj pritegni gledalca.' }, { "title": 'Produkcija', "desc": 'Snemaj in montiraj kvalitetne videe.' }, { "title": 'Monetizacija', "desc": 'Spremeni oglede v prihodke.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Prodajaj fizične izdelke brez skladiščenja (Dropshipping).', "fullDesc": 'Začni svojo spletno trgovino. Nauči se raziskave produktov, sodelovanja z dobavitelji in postavitve Shopify trgovine, ki dejansko prodaja.', "steps": [ { "title": 'Iskanje Produktov', "desc": 'Najdi zmagovalne izdelke.' }, { "title": 'Trgovina', "desc": 'Dizajniraj prodajno stran.' }, { "title": 'Lansiranje', "desc": 'Pripelji promet in izpolni naročila.' } ] }
    ],
    "sq": [
        { "id": 'saas', "icon": '💻', "title": 'Ndërtues SaaS', "shortDesc": 'Krijoni dhe shkallëzoni produkte softuerike që gjenerojnë të ardhura të përsëritura.', "fullDesc": 'Softueri si Shërbim (SaaS) është standardi i artë i të ardhurave dixhitale. Mësoni si të identifikoni zbrazëtirat e tregut, të ndërtoni duke përdorur mjete pa kod ose kod, dhe të shkallëzoni një biznes të bazuar në abonim.', "steps": [ { "title": 'Ideimi', "desc": 'Gjeni probleme fitimprurëse për të zgjidhur.' }, { "title": 'Ndërtimi i MVP', "desc": 'Lansoni një prototip që funksionon shpejt.' }, { "title": 'Shkallëzimi', "desc": 'Fitoni përdorues dhe të ardhura të përsëritura.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Përsosni artin e bindjes për të shitur çdo gjë me fjalë.', "fullDesc": 'Një tekst i mirë bën miliona. Mësoni psikologjinë pas bindjes, si të shkruani faqe uljeje, email-e dhe reklama që konvertojnë të huajt në klientë për tarifa të larta.', "steps": [ { "title": 'Psikologjia', "desc": 'Kuptoni çfarë nxit veprimin.' }, { "title": 'Kornizat', "desc": 'Përsosni strukturat e provuara të shkrimit.' }, { "title": 'Marrja e Klientëve', "desc": 'Siguroni kontrata me pagesë të lartë.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Marketing Dixhital', "shortDesc": 'Drejtoni reklama fitimprurëse dhe menaxhoni rritjen për bizneset.', "fullDesc": 'Çdo biznes ka nevojë për më shumë klientë. Filloni një agjenci (SMMA) duke ndihmuar markat të rriten përmes Facebook Ads, TikTok Ads dhe Google Ads. Kërkesë e lartë, shërbim i shkallëzueshëm.', "steps": [ { "title": 'Strategjia e Reklamave', "desc": 'Mësoni të drejtoni fushata fitimprurëse.' }, { "title": 'Dorëzimi i Shërbimit', "desc": 'Gjeneroni klientë potencialë.' }, { "title": 'Rritja e Agjencisë', "desc": 'Ndërtoni një ekip për punë përmbushëse.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Tregtim Financiar', "shortDesc": 'Analizoni tregjet dhe tregtoni Kripto, Forex ose Indekse.', "fullDesc": 'Përsosni konceptet kryesore të analizës teknike për të lundruar në tregjet financiare. Mësoni menaxhimin e rrezikut, psikologjinë dhe strategjitë për të përfituar nga lëvizjet e tregut në mënyrë të pavarur.', "steps": [ { "title": 'Analiza', "desc": 'Lexoni grafikët dhe strukturën e tregut.' }, { "title": 'Menaxhimi i Rrezikut', "desc": 'Mbroni kapitalin tuaj së pari.' }, { "title": 'Ekzekutimi', "desc": 'Vendosni tregti me probabilitet të lartë.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Krijimi i Përmbajtjes', "shortDesc": 'Ndërtoni një markë personale dhe fitoni nga audienca juaj.', "fullDesc": 'Vëmendja është valuta e re. Mësoni si të krijoni përmbajtje virale në formë të shkurtër, të ndërtoni një ndjekës besnik dhe të fitoni përmes sponsorizimeve, filialeve ose produkteve tuaja.', "steps": [ { "title": 'Skenarë Viralë', "desc": 'Tërhiqni shikuesit menjëherë.' }, { "title": 'Prodhimi', "desc": 'Filmoni dhe editoni klipe me cilësi të lartë.' }, { "title": 'Monetizimi', "desc": 'Ktheni shikimet në të ardhura.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Shisni produkte fizike globalisht pa mbajtur inventar.', "fullDesc": 'Filloni një dyqan dropshipping ose të markuar. Mësoni kërkimin e produkteve, marrëdhëniet me furnitorët dhe si të ndërtoni një vitrinë konvertuese në Shopify.', "steps": [ { "title": 'Gjuetia e Produkteve', "desc": 'Gjeni produkte fituese.' }, { "title": 'Ndërtimi i Dyqanit', "desc": 'Dizenjoni një faqe me konvertim të lartë.' }, { "title": 'Lansimi', "desc": 'Drejtoni trafikun dhe përmbushni porositë.' } ] }
    ],
    "ar": [
        { "id": 'saas', "icon": '💻', "title": 'منشئ SaaS', "shortDesc": 'أنشئ وقم بتوسيع منتجات برمجية تدر دخلاً متكررًا.', "fullDesc": 'البرمجيات كخدمة (SaaS) هي المعيار الذهبي للدخل الرقمي. تعلم كيفية تحديد فجوات السوق، والبناء باستخدام أدوات بدون كود أو بالكود، وتوسيع نطاق عمل يعتمد على الاشتراك.', "steps": [ { "title": 'تكوين الفكرة', "desc": 'ابحث عن مشاكل مربحة لحلها.' }, { "title": 'بناء MVP', "desc": 'أطلق نموذجًا أوليًا عاملاً بسرعة.' }, { "title": 'التوسع', "desc": 'اكتسب مستخدمين وإيرادات متكررة.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'كتابة الإعلانات', "shortDesc": 'أتقن فن الإقناع لبيع أي شيء بالكلمات.', "fullDesc": 'النصوص الجيدة تصنع الملايين. تعلم علم النفس وراء الإقناع، وكيفية كتابة صفحات الهبوط، ورسائل البريد الإلكتروني، والإعلانات التي تحول الغرباء إلى عملاء مقابل رسوم عالية.', "steps": [ { "title": 'علم النفس', "desc": 'افهم ما يدفع لاتخاذ إجراء.' }, { "title": 'الأطر', "desc": 'أتقن هياكل الكتابة المثبتة.' }, { "title": 'اكتساب العملاء', "desc": 'احصل على عقود عالية الأجر.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'التسويق الرقمي', "shortDesc": 'قم بتشغيل إعلانات مربحة وإدارة النمو للشركات.', "fullDesc": 'تحتاج كل شركة إلى المزيد من العملاء. ابدأ وكالة (SMMA) لمساعدة العلامات التجارية على النمو من خلال إعلانات فيسبوك، تيك توك، وجوجل. طلب مرتفع، وخدمة قابلة للتوسع.', "steps": [ { "title": 'استراتيجية الإعلان', "desc": 'تعلم تشغيل حملات مربحة.' }, { "title": 'تقديم الخدمة', "desc": 'ولد عملاء محتملين للعملاء.' }, { "title": 'نمو الوكالة', "desc": 'ابن فريقًا للعمل المُرضي.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'التداول المالي', "shortDesc": 'حلل الأسواق وتداول العملات المشفرة، الفوركس، أو المؤشرات.', "fullDesc": 'أتقن مفاهيم التحليل الفني الرئيسية للتنقل في الأسواق المالية. تعلم إدارة المخاطر، وعلم النفس، والاستراتيجيات للربح من تحركات السوق بشكل مستقل.', "steps": [ { "title": 'التحليل', "desc": 'اقرأ الرسوم البيانية وهيكل السوق.' }, { "title": 'إدارة المخاطر', "desc": 'احمِ رأس مالك أولاً.' }, { "title": 'التنفيذ', "desc": 'نفذ صفقات ذات احتمالية عالية.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'صناعة المحتوى', "shortDesc": 'ابن علامة تجارية شخصية وحقق الدخل من جمهورك.', "fullDesc": 'الانتباه هو العملة الجديدة. تعلم كيفية إنشاء محتوى فيروسي قصير، وبناء متابعين مخلصين، وتحقيق الدخل من خلال الرعاية، أو التسويق بالعمولة، أو منتجاتك الخاصة.', "steps": [ { "title": 'نصوص فيروسية', "desc": 'اجذب المشاهدين فورًا.' }, { "title": 'الإنتاج', "desc": 'صور وحرر مقاطع عالية الجودة.' }, { "title": 'تحقيق الدخل', "desc": 'حول المشاهدات إلى دخل.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'التجارة الإلكترونية', "shortDesc": 'بع منتجات مادية عالميًا دون الاحتفاظ بمخزون.', "fullDesc": 'ابدأ متجر دروبشيبينغ أو علامة تجارية. تعلم البحث عن المنتجات، وعلاقات الموردين، وكيفية بناء واجهة متجر محولة على شوبيفاي.', "steps": [ { "title": 'صيد المنتجات', "desc": 'جد منتجات رابحة.' }, { "title": 'بناء المتجر', "desc": 'صمم موقعًا عالي التحويل.' }, { "title": 'الإطلاق', "desc": 'وجه الزيارات ونفذ الطلبات.' } ] }
    ],
    "be": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Bouwer', "shortDesc": 'Creëer en schaal softwareproducten die terugkerende inkomsten genereren.', "fullDesc": 'Software as a Service (SaaS) is de gouden standaard voor digitaal inkomen. Leer marktlacunes te identificeren, te bouwen met no-code of code tools, en een abonnementsbedrijf op te schalen.', "steps": [ { "title": 'Ideevorming', "desc": 'Vind winstgevende problemen om op te lossen.' }, { "title": 'MVP Bouw', "desc": 'Lanceer snel een werkend prototype.' }, { "title": 'Schalen', "desc": 'Verkrijg gebruikers en terugkerende inkomsten.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Beheers de kunst van overtuiging om alles met woorden te verkopen.', "fullDesc": 'Goede teksten maken miljoenen. Leer de psychologie achter overtuiging, hoe je landingspagina\'s, e-mails en advertenties schrijft die vreemden omzetten in klanten voor hoge tarieven.', "steps": [ { "title": 'Psychologie', "desc": 'Begrijp wat actie aandrijft.' }, { "title": 'Kaders', "desc": 'Beheers bewezen schrijfstructuren.' }, { "title": 'Klantenwerving', "desc": 'Haal goedbetaalde opdrachten binnen.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitale Marketing', "shortDesc": 'Draai winstgevende advertenties en beheer groei voor bedrijven.', "fullDesc": 'Elk bedrijf heeft meer klanten nodig. Start een bureau (SMMA) dat merken helpt groeien via Facebook Ads, TikTok Ads en Google Ads. Veel vraag, schaalbare service.', "steps": [ { "title": 'Advertentiestrategie', "desc": 'Leer winstgevende campagnes te draaien.' }, { "title": 'Dienstverlening', "desc": 'Genereer leads voor klanten.' }, { "title": 'Bureau Groei', "desc": 'Bouw een team voor vervullend werk.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Financiële Handel', "shortDesc": 'Analyseer markten en verhandel Crypto, Forex of Indexen.', "fullDesc": 'Beheers belangrijke technische analyseconcepten om financiële markten te navigeren. Leer risicobeheer, psychologie en strategieën om zelfstandig te profiteren van marktbewegingen.', "steps": [ { "title": 'Analyse', "desc": 'Lees grafieken en marktstructuur.' }, { "title": 'Risicobeheer', "desc": 'Bescherm eerst je kapitaal.' }, { "title": 'Uitvoering', "desc": 'Plaats transacties met hoge waarschijnlijkheid.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Content Creatie', "shortDesc": 'Bouw een persoonlijk merk en verdien aan je publiek.', "fullDesc": 'Aandacht is de nieuwe valuta. Leer hoe je virale short-form content maakt, een trouwe aanhang opbouwt en verdient via sponsoring, affiliates of je eigen producten.', "steps": [ { "title": 'Virale Scripts', "desc": 'Grijp kijkers direct.' }, { "title": 'Productie', "desc": 'Film en edit clips van hoge kwaliteit.' }, { "title": 'Monetarisatie', "desc": 'Zet views om in inkomen.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Verkoop fysieke producten wereldwijd zonder voorraad.', "fullDesc": 'Start een dropshipping of eigen merk webshop. Leer productonderzoek, leveranciersrelaties en hoe je een converterende winkel opbouwt op Shopify.', "steps": [ { "title": 'Product Jacht', "desc": 'Vind winnende producten.' }, { "title": 'Winkel Bouw', "desc": 'Ontwerp een site met hoge conversie.' }, { "title": 'Lancering', "desc": 'Drijf verkeer en vervul bestellingen.' } ] }
    ],
    "bs": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuće prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. Nauči kako prepoznati tržišne praznine, graditi koristeći no-code ili kod alate, i skalirati pretplatnički biznis.', "steps": [ { "title": 'Ideacija', "desc": 'Pronađi profitabilne probleme za rješavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuće prihode.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaš bilo šta riječima.', "fullDesc": 'Dobar tekst donosi milione. Nauči psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi šta pokreće akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaćene ugovore.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba više kupaca. Pokreni agenciju (SMMA) pomažući brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potražnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'Nauči voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'Generiši lidove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajući rad.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Finansijsko Trgovanje', "shortDesc": 'Analiziraj tržišta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj ključne koncepte tehničke analize za navigaciju finansijskim tržištima. Nauči upravljanje rizikom, psihologiju i strategije da profitiraš od tržišnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'Čitaj grafikone i strukturu tržišta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaštiti svoj kapital.' }, { "title": 'Izvršenje', "desc": 'Postavljaj trgovine visoke vjerovatnoće.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Kreiranje Sadržaja', "shortDesc": 'Izgradi lični brend i monetizuj svoju publiku.', "fullDesc": 'Pažnja je nova valuta. Nauči kako kreirati viralni kratki sadržaj, izgraditi lojalne pratioce i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledaoce.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visokog kvaliteta.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Prodaji fizičke proizvode globalno bez držanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. Nauči istraživanje proizvoda, odnose s dobavljačima i kako izgraditi konvertujuću trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'Pronađi pobjedničke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi saobraćaj i ispuni narudžbe.' } ] }
    ],
    "zh": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS 构建者', "shortDesc": '创建并扩展产生经常性收入的软件产品。', "fullDesc": '软件即服务 (SaaS) 是数字收入的黄金标准。学习如何识别市场空白，使用无代码或代码工具构建，并扩展基于订阅的业务。', "steps": [ { "title": '构思', "desc": '找到有利可图的问题来解决。' }, { "title": 'MVP 构建', "desc": '快速推出可用的原型。' }, { "title": '扩展', "desc": '获取用户和经常性收入。' } ] },
        { "id": 'copy', "icon": '✍️', "title": '文案写作', "shortDesc": '掌握说服的艺术，用文字销售任何东西。', "fullDesc": '好的文案能创造数百万价值。学习说服背后的心理学，如何撰写着陆页、电子邮件和广告，将陌生人转化为高付费客户。', "steps": [ { "title": '心理学', "desc": '了解驱动行动的因素。' }, { "title": '框架', "desc": '掌握经过验证的写作结构。' }, { "title": '客户获取', "desc": '获得高薪长期合同。' } ] },
        { "id": 'marketing', "icon": '📈', "title": '数字营销', "shortDesc": '为企业运营盈利广告并管理增长。', "fullDesc": '每个企业都需要更多客户。通过 Facebook 广告、TikTok 广告和 Google 广告帮助品牌增长，创办一家代理机构 (SMMA)。需求量大，服务可扩展。', "steps": [ { "title": '广告策略', "desc": '学习运营盈利的活动。' }, { "title": '服务交付', "desc": '为客户生成潜在客户。' }, { "title": '代理机构增长', "desc": '建立团队以完成工作。' } ] },
        { "id": 'trading', "icon": '📊', "title": '金融交易', "shortDesc": '分析市场并交易加密货币、外汇或指数。', "fullDesc": '掌握关键的技术分析概念以驾驭金融市场。学习风险管理、心理学和策略，以独立从市场波动中获利。', "steps": [ { "title": '分析', "desc": '阅读图表和市场结构。' }, { "title": '风险管理', "desc": '首先保护你的资本。' }, { "title": '执行', "desc": '进行高概率交易。' } ] },
        { "id": 'content', "icon": '🎥', "title": '内容创作', "shortDesc": '建立个人品牌并从受众中获利。', "fullDesc": '注意力是新的货币。学习如何创作病毒式短视频内容，建立忠实的追随者，并通过赞助、联盟或自己的产品获利。', "steps": [ { "title": '病毒脚背', "desc": '立即吸引观众。' }, { "title": '制作', "desc": '拍摄和剪辑高质量片段。' }, { "title": '变现', "desc": '将观看转化为收入。' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": '电子商务', "shortDesc": '在全球范围内销售实体产品，无需持有库存。', "fullDesc": '开设一家代发货或品牌电子商务商店。学习产品研究、供应商关系，以及如何在 Shopify 上建立高转化率的店面。', "steps": [ { "title": '产品搜寻', "desc": '找到获胜产品。' }, { "title": '商店构建', "desc": '设计高转化率网站。' }, { "title": '发布', "desc": '驱动流量并履行订单。' } ] }
    ],
    "hr": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuće prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. Nauči kako prepoznati tržišne praznine, graditi koristeći no-code ili kod alate, i skalirati pretplatnički biznis.', "steps": [ { "title": 'Ideacija', "desc": 'Pronađi profitabilne probleme za rješavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuće prihode.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaš bilo što riječima.', "fullDesc": 'Dobar tekst donosi milijune. Nauči psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi što pokreće akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaćene ugovore.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba više kupaca. Pokreni agenciju (SMMA) pomažući brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potražnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'Nauči voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'Generiraj leadove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajući rad.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Financijsko Trgovanje', "shortDesc": 'Analiziraj tržišta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj ključne koncepte tehničke analize za navigaciju financijskim tržištima. Nauči upravljanje rizikom, psihologiju i strategije da profitiraš od tržišnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'Čitaj grafikone i strukturu tržišta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaštiti svoj kapital.' }, { "title": 'Izvršenje', "desc": 'Postavljaj trgovine visoke vjerojatnosti.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Kreiranje Sadržaja', "shortDesc": 'Izgradi osobni brend i monetiziraj svoju publiku.', "fullDesc": 'Pažnja je nova valuta. Nauči kako kreirati viralni kratki sadržaj, izgraditi lojalne pratitelje i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledatelje.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visoke kvalitete.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Prodaji fizičke proizvode globalno bez držanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. Nauči istraživanje proizvoda, odnose s dobavljačima i kako izgraditi konvertirajuću trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'Pronađi pobjedničke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi promet i ispuni narudžbe.' } ] }
    ],
    "cs": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Tvůrce', "shortDesc": 'Vytvářejte a škálujte softwarové produkty generující opakované příjmy.', "fullDesc": 'Software as a Service (SaaS) je zlatý standard digitálního příjmu. Naučte se identifikovat mezery na trhu, budovat pomocí no-code nebo kódovacích nástrojů a škálovat předplatitelské podnikání.', "steps": [ { "title": 'Nápad', "desc": 'Najděte ziskové problémy k řešení.' }, { "title": 'Tvorba MVP', "desc": 'Rychle spusťte funkční prototyp.' }, { "title": 'Škálování', "desc": 'Získejte uživatele a opakované příjmy.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Ovládněte umění přesvědčování a prodávejte cokoliv slovy.', "fullDesc": 'Dobrý text vydělává miliony. Poznejte psychologii přesvědčování, jak psát vstupní stránky, e-maily a reklamy, které mění cizince v zákazníky za vysoké poplatky.', "steps": [ { "title": 'Psychologie', "desc": 'Pochopte, co pohání akci.' }, { "title": 'Rámce', "desc": 'Ovládněte osvědčené struktury psaní.' }, { "title": 'Získávání klientů', "desc": 'Získejte vysoce placené zakázky.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitální Marketing', "shortDesc": 'Spravujte ziskové reklamy a řiďte růst firem.', "fullDesc": 'Každá firma potřebuje více zákazníků. Založte agenturu (SMMA) pomáhající značkám růst prostřednictvím Facebook Ads, TikTok Ads a Google Ads. Vysoká poptávka, škálovatelná služba.', "steps": [ { "title": 'Reklamní strategie', "desc": 'Naučte se řídit ziskové kampaně.' }, { "title": 'Poskytování služeb', "desc": 'Generujte leady pro klientů.' }, { "title": 'Růst agentury', "desc": 'Vybudujte tým pro naplňující práci.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Finanční Obchodování', "shortDesc": 'Analyzujte trhy a obchodujte Krypto, Forex nebo Indexy.', "fullDesc": 'Ovládněte klíčové koncepty technické analýzy pro navigaci na finančních trzích. Naučte se řízení rizik, psychologii a strategie, jak nezávisle profitovat z tržních pohybů.', "steps": [ { "title": 'Analýza', "desc": 'Čtěte grafy a strukturu trhu.' }, { "title": 'Řízení rizik', "desc": 'Nejprve chraňte svůj kapitál.' }, { "title": 'Exekuce', "desc": 'Provádějte obchody s vysokou pravděpodobností.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Tvorba Obsahu', "shortDesc": 'Vybudujte osobní značku a monetizujte své publikum.', "fullDesc": 'Pozornost je nová měna. Naučte se vytvářet virální krátká videa, budovat věrné sledující a vydělávat prostřednictvím sponzorství, affiliate nebo vlastních produktů.', "steps": [ { "title": 'Virální scénáře', "desc": 'Okamžitě zaujměte diváky.' }, { "title": 'Produkce', "desc": 'Natáčejte a stříhejte kvalitní klipy.' }, { "title": 'Monetizace', "desc": 'Proměňte zhlédnutí v příjem.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Prodávejte fyzické produkty globálně bez držení zásob.', "fullDesc": 'Spusťte dropshippingový nebo značkový e-shop. Naučte se průzkum produktů, vztahy s dodavateli a jak vybudovat konverzní obchod na Shopify.', "steps": [ { "title": 'Hledání produktů', "desc": 'Najděte vítězné produkty.' }, { "title": 'Stavba obchodu', "desc": 'Navrhněte web s vysokou konverzí.' }, { "title": 'Spuštění', "desc": 'Přiveďte návštevnost a vyřizujte objednávky.' } ] }
    ],
