
    "ru": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Создатель', "shortDesc": 'Создавайте и масштабируйте программные продукты с регулярным доходом.', "fullDesc": 'Программное обеспечение как услуга (SaaS) — это золотой стандарт цифрового дохода. Узнайте, как находить рыночные ниши, создавать с помощью no-code или кода и масштабировать бизнес по подписке.', "steps": [ { "title": 'Идея', "desc": 'Найдите прибыльные проблемы для решения.' }, { "title": 'Создание MVP', "desc": 'Быстро запустите работающий прототип.' }, { "title": 'Масштабирование', "desc": 'Привлекайте пользователей и доход.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Копирайтинг', "shortDesc": 'Овладейте искусством убеждения, чтобы продавать что угодно словами.', "fullDesc": 'Хороший текст приносит миллионы. Изучите психологию убеждения, как писать целевые страницы, электронные письма и рекламу, которые превращают незнакомцев в клиентов за высокие гонорары.', "steps": [ { "title": 'Психология', "desc": 'Поймите, что движет действием.' }, { "title": 'Структуры', "desc": 'Овладейте проверенными структурами письма.' }, { "title": 'Клиенты', "desc": 'Получайте высокооплачиваемые заказы.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Цифровой Маркетинг', "shortDesc": 'Запускайте прибыльную рекламу и управляйте ростом компаний.', "fullDesc": 'Каждому бизнесу нужно больше клиентов. Откройте агентство (SMMA), помогая брендам расти через Facebook Ads, TikTok Ads и Google Ads. Высокий спрос, масштабируемость.', "steps": [ { "title": 'Стратегия', "desc": 'Учитесь запускать прибыльные кампании.' }, { "title": 'Услуги', "desc": 'Генерируйте лиды для клиентов.' }, { "title": 'Рост', "desc": 'Создайте команду для работы.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Трейдинг', "shortDesc": 'Анализируйте рынки и торгуйте Крипто, Форекс или Индексами.', "fullDesc": 'Овладейте ключевыми концепциями технического анализа. Изучите управление рисками, психологию и стратегии, чтобы самостоятельно получать прибыль от движений рынка.', "steps": [ { "title": 'Анализ', "desc": 'Читайте графики и структуру рынка.' }, { "title": 'Риск', "desc": 'Сначала защитите свой капитал.' }, { "title": 'Исполнение', "desc": 'Совершайте сделки с высокой вероятностью.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Создание Контента', "shortDesc": 'Создайте личный бренд и монетизируйте аудиторию.', "fullDesc": 'Внимание — это новая валюта. Узнайте, как создавать вирусный короткий контент, набирать лояльных подписчиков и зарабатывать на спонсорстве или собственных продуктах.', "steps": [ { "title": 'Вирусные Сценарии', "desc": 'Мгновенно цепляйте зрителей.' }, { "title": 'Продакшн', "desc": 'Снимайте и монтируйте качественные клипы.' }, { "title": 'Монетизация', "desc": 'Превращайте просмотры в доход.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Продавайте физические товары по всему миру без склада.', "fullDesc": 'Запустите дропшиппинг или брендовый магазин. Изучите поиск продуктов, отношения с поставщиками и как создать конверсионный магазин на Shopify.', "steps": [ { "title": 'Поиск Продукта', "desc": 'Найдите выигрышные товары.' }, { "title": 'Создание Магазина', "desc": 'Создайте сайт с высокой конверсией.' }, { "title": 'Запуск', "desc": 'Привлекайте трафик и выполняйте заказы.' } ] }
    ],
    "sr": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Graditelj', "shortDesc": 'Kreiraj i skaliraj softverske proizvode koji donose ponavljajuće prihode.', "fullDesc": 'Software as a Service (SaaS) je zlatni standard digitalnog prihoda. Nauči kako prepoznati tržišne praznine, graditi koristeći no-code ili kod alate, i skalirati pretplatnički biznis.', "steps": [ { "title": 'Ideacija', "desc": 'Pronađi profitabilne probleme za rješavanje.' }, { "title": 'MVP Izrada', "desc": 'Brzo lansiraj funkcionalan prototip.' }, { "title": 'Skaliranje', "desc": 'Stekni korisnike i ponavljajuće prihode.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Savladaj umjetnost uvjeravanja da prodaš bilo šta riječima.', "fullDesc": 'Dobar tekst donosi milione. Nauči psihologiju iza uvjeravanja, kako pisati landing stranice, emailove i oglase koji pretvaraju strance u kupce za visoke honorare.', "steps": [ { "title": 'Psihologija', "desc": 'Razumi šta pokreće akciju.' }, { "title": 'Okviri', "desc": 'Savladaj dokazane strukture pisanja.' }, { "title": 'Akvizicija Klijenata', "desc": 'Osiguraj visoko plaćene ugovore.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitalni Marketing', "shortDesc": 'Vodi profitabilne oglase i upravljaj rastom za biznise.', "fullDesc": 'Svaki biznis treba više kupaca. Pokreni agenciju (SMMA) pomažući brendovima da rastu kroz Facebook Ads, TikTok Ads i Google Ads. Velika potražnja, skalabilna usluga.', "steps": [ { "title": 'Strategija Oglasa', "desc": 'Nauči voditi profitabilne kampanje.' }, { "title": 'Isporuka Usluge', "desc": 'Generiši lidove za klijente.' }, { "title": 'Rast Agencije', "desc": 'Izgradi tim za ispunjavajući rad.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Finansijsko Trgovanje', "shortDesc": 'Analiziraj tržišta i trguj Kripto, Forex ili Indeksima.', "fullDesc": 'Savladaj ključne koncepte tehničke analize za navigaciju finansijskim tržištima. Nauči upravljanje rizikom, psihologiju i strategije da profitiraš od tržišnih kretanja samostalno.', "steps": [ { "title": 'Analiza', "desc": 'Čitaj grafikone i strukturu tržišta.' }, { "title": 'Upravljanje Rizikom', "desc": 'Prvo zaštiti svoj kapital.' }, { "title": 'Izvršenje', "desc": 'Postavljaj trgovine visoke vjerovatnoće.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Kreiranje Sadržaja', "shortDesc": 'Izgradi lični brend i monetizuj svoju publiku.', "fullDesc": 'Pažnja je nova valuta. Nauči kako kreirati viralni kratki sadržaj, izgraditi lojalne pratioce i zaraditi kroz sponzorstva, partnere ili vlastite proizvode.', "steps": [ { "title": 'Viralni Skripti', "desc": 'Odmah privuci gledaoce.' }, { "title": 'Produkcija', "desc": 'Snimaj i montiraj klipove visokog kvaliteta.' }, { "title": 'Monetizacija', "desc": 'Pretvori preglede u prihod.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Prodaji fizičke proizvode globalno bez držanja zaliha.', "fullDesc": 'Pokreni dropshipping ili brendiranu web trgovinu. Nauči istraživanje proizvoda, odnose s dobavljačima i kako izgraditi konvertujuću trgovinu na Shopify-u.', "steps": [ { "title": 'Potraga za Proizvodima', "desc": 'Pronađi pobjedničke proizvode.' }, { "title": 'Izrada Trgovine', "desc": 'Dizajniraj stranicu s visokom konverzijom.' }, { "title": 'Lansiranje', "desc": 'Dovedi saobraćaj i ispuni narudžbe.' } ] }
    ],
    "sk": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Tvorca', "shortDesc": 'Vytvárajte a škálujte softvérové produkty, ktoré generujú opakujúce sa príjmy.', "fullDesc": 'Software as a Service (SaaS) je zlatý štandard digitálneho príjmu. Naučte sa identifikovať medzery na trhu, budovať pomocou no-code alebo kódovacích nástrojov a škálovať predplatiteľské podnikanie.', "steps": [ { "title": 'Idea', "desc": 'Nájdite ziskové problémy na riešenie.' }, { "title": 'Tvorba MVP', "desc": 'Rýchlo spustite funkčný prototyp.' }, { "title": 'Škálovanie', "desc": 'Získajte používateľov a opakujúce sa príjmy.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Ovládnite umenie presviedčania a predávajte čokoľvek slovami.', "fullDesc": 'Dobrý text zarába milióny. Spoznajte psychológiu presviedčania, ako písať vstupné stránky, e-maily a reklamy, ktoré menia cudzincov na zákazníkov za vysoké poplatky.', "steps": [ { "title": 'Psychológia', "desc": 'Pochopte, čo poháňa akciu.' }, { "title": 'Rámce', "desc": 'Ovládnite osvedčené štruktúry písania.' }, { "title": 'Získavanie klientov', "desc": 'Získajte vysoko platené zákazky.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Digitálny Marketing', "shortDesc": 'Spravujte ziskové reklamy a riaďte rast firiem.', "fullDesc": 'Každá firma potrebuje viac zákazníkov. Založte agentúru (SMMA) pomáhajúcu značkám rásť prostredníctvom Facebook Ads, TikTok Ads a Google Ads. Vysoký dopyt, škálovateľná služba.', "steps": [ { "title": 'Reklamná stratégia', "desc": 'Naučte sa riadiť ziskové kampane.' }, { "title": 'Poskytovanie služieb', "desc": 'Generujte leady pre klientov.' }, { "title": 'Rast agentúry', "desc": 'Vybudujte tím pre naplňujúcu prácu.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Finančné Obchodovanie', "shortDesc": 'Analyzujte trhy a obchodujte Krypto, Forex alebo Indexy.', "fullDesc": 'Ovládnite kľúčové koncepty technickej analýzy pre navigáciu na finančných trhoch. Naučte sa riadenie rizík, psychológiu a stratégie, ako nezávisle profitovať z trhových pohybov.', "steps": [ { "title": 'Analýza', "desc": 'Čítajte grafy a štruktúru trhu.' }, { "title": 'Riadenie rizík', "desc": 'Najprv chráňte svoj kapitál.' }, { "title": 'Exekúcia', "desc": 'Vykonávajte obchody s vysokou pravdepodobnosťou.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Tvorba Obsahu', "shortDesc": 'Vybudujte osobnú značku a monetizujte svoje publikum.', "fullDesc": 'Pozornosť je nová mena. Naučte sa vytvárať virálne krátke videá, budovať verných sledovateľov a zarábať prostredníctvom sponzorstva, affiliate alebo vlastných produktov.', "steps": [ { "title": 'Virálne scenáre', "desc": 'Okamžite zaujmite divákov.' }, { "title": 'Produkcia', "desc": 'Natáčajte a strihajte kvalitné klipy.' }, { "title": 'Monetizácia', "desc": 'Premeňte zhliadnutia na príjem.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Predávajte fyzické produkty globálne bez držania zásob.', "fullDesc": 'Spustite dropshippingový alebo značkový e-shop. Naučte sa prieskum produktov, vzťahy s dodávateľmi a ako vybudovať konverzný obchod na Shopify.', "steps": [ { "title": 'Hľadanie produktov', "desc": 'Nájdite víťazné produkty.' }, { "title": 'Stavba obchodu', "desc": 'Navrhnite web s vysokou konverziou.' }, { "title": 'Spustenie', "desc": 'Priveďte návštevnosť a vybavujte objednávky.' } ] }
    ],
    "es": [
        { "id": 'saas', "icon": '💻', "title": 'Creador SaaS', "shortDesc": 'Crea y escala productos de software que generen ingresos recurrentes.', "fullDesc": 'El Software como Servicio (SaaS) es el estándar de oro de los ingresos digitales. Aprende a identificar huecos en el mercado, construir con herramientas sin código o con código, y escalar un negocio de suscripción.', "steps": [ { "title": 'Ideación', "desc": 'Encuentra problemas rentables para resolver.' }, { "title": 'Construcción MVP', "desc": 'Lanza un prototipo funcional rápido.' }, { "title": 'Escalado', "desc": 'Adquiere usuarios e ingresos recurrentes.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Copywriting', "shortDesc": 'Domina el arte de la persuasión para vender cualquier cosa con palabras.', "fullDesc": 'Un buen texto genera millones. Aprende la psicología detrás de la persuasión, cómo escribir páginas de aterrizaje, correos electrónicos y anuncios que conviertan extraños en clientes.', "steps": [ { "title": 'Psicología', "desc": 'Entiende qué impulsa la acción.' }, { "title": 'Marcos', "desc": 'Domina estructuras de escritura probadas.' }, { "title": 'Adquisición', "desc": 'Consigue contratos bien pagados.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Marketing Digital', "shortDesc": 'Ejecuta anuncios rentables y gestiona el crecimiento de empresas.', "fullDesc": 'Todo negocio necesita más clientes. Inicia una agencia (SMMA) ayudando a marcas a crecer a través de Facebook Ads, TikTok Ads y Google Ads. Alta demanda, servicio escalable.', "steps": [ { "title": 'Estrategia', "desc": 'Aprende a ejecutar campañas rentables.' }, { "title": 'Entrega', "desc": 'Genera clientes potenciales.' }, { "title": 'Crecimiento', "desc": 'Construye un equipo para el trabajo.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Trading Financiero', "shortDesc": 'Analiza mercados y opera Cripto, Forex o Índices.', "fullDesc": 'Domina conceptos clave de análisis técnico para navegar los mercados financieros. Aprende gestión de riesgos, psicología y estrategias para beneficiarte de los movimientos del mercado.', "steps": [ { "title": 'Análisis', "desc": 'Lee gráficos y estructura de mercado.' }, { "title": 'Riesgo', "desc": 'Protege tu capital primero.' }, { "title": 'Ejecución', "desc": 'Coloca operaciones de alta probabilidad.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Creación de Contenido', "shortDesc": 'Construye una marca personal y monetiza tu audiencia.', "fullDesc": 'La atención es la nueva moneda. Aprende a crear contenido viral corto, construir seguidores leales y ganar a través de patrocinios, afiliados o tus propios productos.', "steps": [ { "title": 'Guiones Virales', "desc": 'Engancha a los espectadores al instante.' }, { "title": 'Producción', "desc": 'Graba y edita clips de alta calidad.' }, { "title": 'Monetización', "desc": 'Convierte visitas en ingresos.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Vende productos físicos globalmente sin inventario.', "fullDesc": 'Inicia una tienda de dropshipping o de marca. Aprende investigación de productos, relaciones con proveedores y cómo construir una tienda que convierta en Shopify.', "steps": [ { "title": 'Caza de Productos', "desc": 'Encuentra productos ganadores.' }, { "title": 'Construcción', "desc": 'Diseña un sitio de alta conversión.' }, { "title": 'Lanzamiento', "desc": 'Genera tráfico y cumple pedidos.' } ] }
    ],
    "uk": [
        { "id": 'saas', "icon": '💻', "title": 'SaaS Розробник', "shortDesc": 'Створюйте та масштабуйте програмні продукти з регулярним доходом.', "fullDesc": 'Програмне забезпечення як послуга (SaaS) — це золотий стандарт цифрового доходу. Дізнайтеся, як знаходити ринкові ніші, створювати за допомогою no-code або коду та масштабувати бізнес за передплатою.', "steps": [ { "title": 'Ідея', "desc": 'Знайдіть прибуткові проблеми для вирішення.' }, { "title": 'Створення MVP', "desc": 'Швидко запустіть працюючий прототип.' }, { "title": 'Масштабування', "desc": 'Залучайте користувачів та дохід.' } ] },
        { "id": 'copy', "icon": '✍️', "title": 'Копірайтинг', "shortDesc": 'Опануйте мистецтво переконання, щоб продавати будь-що словами.', "fullDesc": 'Хороший текст приносить мільйони. Вивчіть психологію переконання, як писати цільові сторінки, електронні листи та рекламу, які перетворюють незнайомців на клієнтів за високі гонорари.', "steps": [ { "title": 'Психологія', "desc": 'Зрозумійте, що спонукає до дії.' }, { "title": 'Структури', "desc": 'Опануйте перевірені структури письма.' }, { "title": 'Клієнти', "desc": 'Отримуйте високооплачувані замовлення.' } ] },
        { "id": 'marketing', "icon": '📈', "title": 'Цифровий Маркетинг', "shortDesc": 'Запускайте прибуткову рекламу та керуйте зростанням компаній.', "fullDesc": 'Кожному бізнесу потрібно більше клієнтів. Відкрийте агентство (SMMA), допомагаючи брендам рости через Facebook Ads, TikTok Ads та Google Ads. Високий попит, масштабованість.', "steps": [ { "title": 'Стратегія', "desc": 'Вчіться запускати прибуткові кампанії.' }, { "title": 'Послуги', "desc": 'Генеруйте ліди для клієнтів.' }, { "title": 'Ріст', "desc": 'Створіть команду для роботи.' } ] },
        { "id": 'trading', "icon": '📊', "title": 'Трейдинг', "shortDesc": 'Аналізуйте ринки та торгуйте Крипто, Форекс або Індексами.', "fullDesc": 'Опануйте ключові концепції технічного аналізу. Вивчіть управління ризиками, психологію та стратегії, щоб самостійно отримувати прибуток від рухів ринку.', "steps": [ { "title": 'Аналіз', "desc": 'Читайте графіки та структуру ринку.' }, { "title": 'Ризик', "desc": 'Спочатку захистіть свій капітал.' }, { "title": 'Виконання', "desc": 'Здійснюйте угоди з високою ймовірністю.' } ] },
        { "id": 'content', "icon": '🎥', "title": 'Створення Контенту', "shortDesc": 'Створіть особистий бренд та монетизуйте аудиторію.', "fullDesc": 'Увага — це нова валюта. Дізнайтеся, як створювати вірусний короткий контент, набирати лояльних підписників та заробляти на спонсорстві або власних продуктах.', "steps": [ { "title": 'Вірусні Сценарії', "desc": 'Миттєво чіпляйте глядачів.' }, { "title": 'Продакшн', "desc": 'Знімайте та монтуйте якісні кліпи.' }, { "title": 'Монетизація', "desc": 'Перетворюйте перегляди на дохід.' } ] },
        { "id": 'ecom', "icon": '🛍️', "title": 'E-commerce', "shortDesc": 'Продавайте фізичні товари по всьому світу без складу.', "fullDesc": 'Запустіть дропшиппінг або брендовий магазин. Вивчіть пошук продуктів, відносини з постачальниками та як створити конверсійний магазин на Shopify.', "steps": [ { "title": 'Пошук Продукту', "desc": 'Знайдіть виграшні товари.' }, { "title": 'Створення Магазину', "desc": 'Створіть сайт з високою конверсією.' }, { "title": 'Запуск', "desc": 'Залучайте трафік та виконуйте замовлення.' } ] }
    ]
}
